name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    needs: [build-frontend]
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.43

      - name: Cache bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Test
        run: bun run test

  
  push-backend-and-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ancestree2025/server:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./client/Dockerfile
          tags: ancestree2025/client:latest